# This requires a suggested change that nas not been merged yet to this file: 
# /usr/lib/python2.7/site-packages/ansible/modules/net_tools/nmcli.py
# Here is the pull request: 
# https://github.com/ansible/ansible/pull/58115/files

- name: Delete the old network ethernet connection ({{NETWORK_ETHERNET_CONNECTION}}). 
  nmcli: 
   conn_name: "{{NETWORK_ETHERNET_CONNECTION}}" 
   state: absent
- name: Bring up a new bridge connection ({{NETWORK_BRIDGE_CONNECTION}}). 
  nmcli: 
    type: bridge
    mac: "{{NETWORK_BRIDGE_MAC}}" 
    conn_name: "{{NETWORK_BRIDGE_CONNECTION}}" 
    ifname: "{{NETWORK_ETHERNET_DEVICE}}"
    ip4: "{{NETWORK_IP_ADDRESS}}"
    gw4: "{{NETWORK_GATEWAY}}"
    dns4: "{{NETWORK_DNS}}"
    state: present
- name: Bring up a new bridge-slave connection ({{NETWORK_BRIDGE_SLAVE_CONNECTION}}). 
  nmcli: 
    type: bridge-slave
    conn_name: "{{NETWORK_BRIDGE_SLAVE_CONNECTION}}" 
    ifname: "{{NETWORK_ETHERNET_DEVICE}}"
    master: "{{NETWORK_BRIDGE_CONNECTION}}"
    state: present


